changed trigger command and added mail and web hosting info
ocf/ircbot pull request #202
Opened 2021-04-19 03:37 UTC by snarain01

Decided to change the trigger from "!group" and "!subdomain" to "create: group" and "create: subdomain" for consistency. Also added the ability for it to distinguish mail vhost and web vhost.

2021-04-19 07:12 UTC, ja5087 requested changes
First pass on this. Thinking ahead, a lot of this functionality can be moved to ocflib at some point but that's not a blocker. Thanks for the changes! Looking forward to this in IRC.

2021-04-19 07:12 UTC, ja5087 commented on ircbot/plugin/group.py
> +    if not any([re.search(valid_ending, s) is not None for valid_ending in valid_endings]):
I would probably write this as `all([search is None])` (this is DeMorgan's law), but it's up to you

2021-04-19 07:12 UTC, ja5087 commented on ircbot/plugin/group.py
> +    if not any([re.search(valid_ending, s) is not None for valid_ending in valid_endings]):
I recommend making the regex more strict or use `rfind` instead after `strip`ping the input, since you seem to be trying to search for a suffix. The `.` will match everything under the sun:

```
>>> re.search('.berkeley.edu', 'lberkeleyledu')
<re.Match object; span=(0, 13), match='lberkeleyledu'>
```

2021-04-19 07:12 UTC, ja5087 commented on ircbot/plugin/group.py
> +            continue
same problem here, although most users do not have multiple mail vhosts

2021-04-19 19:02 UTC, snarain01 commented on ircbot/plugin/group.py
> +    mail_vhost = vhosts_for_user(user) != set()
Yeah, I got rid of this part entirely

2021-04-19 19:03 UTC, snarain01 commented on ircbot/plugin/group.py
>              subdomain = vhost[0]
I did not know that, the new logic also adds the aliases to the response

2021-04-19 19:03 UTC, snarain01 commented on ircbot/plugin/group.py
> +    if not any([re.search(valid_ending, s) is not None for valid_ending in valid_endings]):
Yeah, rfind is definitely better! I didn't know it existed

2021-04-19 19:06 UTC, snarain01 commented on ircbot/plugin/group.py
> +            continue
Yeah, I found this interesting since the vhost-mail.conf has single line entries with only one domain and account. After some searching around I found a few accounts that had multiple vhosts (like uav). I was able to fix this too

2021-04-19 19:09 UTC, snarain01 commented
Hey jaw! Thanks for looking through this. I pushed a new version that closely follows the format you recommended. I tested it out with multiple accounts and it seems to function well.

2021-04-19 19:13 UTC, snarain01 commented
Also, I decided to change the "create: subdomain" to "create: domain" since we offer vhosting for non .berkeley.edu domains as well.

2021-04-22 22:47 UTC, cg505 commented on ircbot/plugin/group.py
> +    if get_tld('http://www.' + s, fail_silently=True) is None:
why `www.`?

2021-04-23 01:09 UTC, saurabhnarain commented on ircbot/plugin/group.py
> +    if get_tld('http://www.' + s, fail_silently=True) is None:
Ah yeah, I thought that get_tld would only work if `www.` was there, but I just tested get_tld, and it works without the `www.`.

2021-04-27 03:42 UTC, cg505 approved these changes
I think you should try to test this on k8s if you haven't - I think you'll be fine but I'm not sure if some of these ocflib function will work correctly from within docker (e.g. if they expect certain local config files or something)

2021-04-27 03:55 UTC, ja5087 commented
I already mounted the OCF local folder into the Docker container so it will probably work

2021-04-27 03:56 UTC, ja5087 approved these changes

2021-04-27 03:56 UTC, merged